### ISSUE TITLE
[GitHub] Design and implement GitHub repository with DEMO & Integration scheme

### ISSUE THREAD

**Issue by yuyuqq** [space-station-os/space_station_os#5]
### User story
- Design and implement GitHub repository  with DEMO & Integration scheme
### Acceptance criteria
- Propose GitHub repository structure, and discuss in the team 
- After decisions is made, reorganize GitHub

**Comment by yuyuqq** [comment]
Here is a proposal of GitHub repository structure design:
Will be discussed in the rechnical meeting in Dec. 16th 2024.

![Image](https://github.com/user-attachments/assets/064dbdf0-8b02-4b54-9f1d-5b58c0f6a97b)

**Comment by Ohara124c41** [comment]
The added management and maintenance costs are worth the design approach. We will be able to utilize an iterative structure while focusing on the most recent content and archiving/redacting unused content. We just have to make sure we never break the integration modules.

**Comment by yuyuqq** [comment]
I have completed moving demo#1 to its own repo. The repo name is "demo_nauka_incident2021_estimate." The content is the same as the original "space_station_gnc" in the "space_station_os" repo. 

Demo creaters can go ahead and start working on creating demos by adding a new repo.

**The demo repository shall have the prefix of ""demo_" so that people can find it is for a demo.**
I will let people know in the next technical meeting and documentation site.

I left the original space_stattion_os repo as it was we could start modifying for the integration.
